### ISSUE TITLE
dwarf bonus languages are not listed

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#919] opened 2019-08-20 19:17 UTC
if i create a dwarf and i have a bonus in int i try to add a language bonus but there aren't any languages in the list for languages

**Comment by BahamutDragon** [comment] 2019-08-21 09:49
Have you selected the dwarf subrace?

**Comment by nevarim** [comment] 2019-08-24 10:44
no template, simply assigned dwarf race, with  other races works

**Comment by BahamutDragon** [comment] 2019-08-29 05:11
It appears to work for me, loading the core books (PH, MM, DMG):

![image](https://user-images.githubusercontent.com/4307487/63911871-b2bb7e00-c9e0-11e9-9076-213aa093aa67.png)

**Comment by BahamutDragon** [comment] 2019-09-15 01:46
Unable to reproduce. Closing.

**Closed by BahamutDragon** 2019-09-15 01:46 UTC
