### ISSUE TITLE
Cstp issue

### ISSUE THREAD

**Issue by CyanideY** [BahamutDragon/pcgen#227] opened 2015-06-25 19:34 UTC
after looking around i found a section in the ACF missing. the Convert spell to power ACF adds spellcraft as a erudite class skill and this function appears to be missing.

**Comment by BahamutDragon** [comment] 2015-06-25 21:00
Class Skill added

**Comment by BahamutDragon** [comment] 2015-07-02 06:07
Working for you?

**Comment by CyanideY** [comment] 2015-07-02 12:38
Yes, the class skill is in there and working. thanks for all your help on
this.

**Comment by CyanideY** [comment] 2015-07-03 00:33
gave the player wanting to use this the files and he was building his character and found another issue. this one is with the erudite base class and the Cstp ACF. the erudite base class dose not get access to discipline powers like it should. The issue with the Cstp is that on spell tab no spell actuality show up there.

**Comment by BahamutDragon** [comment] 2015-07-03 23:55
Mate, 

Reviewing the last post. Erudite class does not have any primary disciplines, the text mentions it to determine how hard to obtain a spell. What I think your request here is asking for a method to add any arcane spell to the erudite spell list. That is a very big request and well beyond any easy coding. 

The issue is making a zero cost ability for each spell allowed and assigning it to the erudite spell list.

Convert Spell to Power
States: Your training has included basic magical theory as well as the usual psionic training. 

Replaces: You lose your 1st-level bonus feat. 

Benefit: You add Spellcraft to your class skill list, which allows you to attempt to convert an arcane spell into a power you can add to your repertoire. You treat the spell as a discipline power for the basis of learning it, and you must first succeed on a Spellcraft check (DC 15 + the spell's level) and then a Psicraft check as per the normal rules of learning a discipline power (see page 154 of Complete Psionic). Each spell costs a certain number of power points to manifest. The higher the level of the spell, the more power points it costs. The table below describes each spell's cost. 0-level spells cost no power points to manifest. Instead you may manifest a number of 0-level spells each day equal to three + the number of power points gained by that class at 1st level. The erudite uses her manifester level for determining the effects of the spell being manifested, with one significant exception. Spells that deal a number of dice of damage based on caster level (such as magic missile, searing light, or lightning bolt) deal damage as if cast by a character of the minimum level of the class capable of casting the spell. Spells whose damage is partially based on caster level, but that don't deal a number of dice of damage based on caster level (such as produce flame or an inflict spell) use the erudite's normal manifester level to determine damage. Use the erudite's normal manifester level for all other effects, including range and duration.

**Comment by CyanideY** [comment] 2015-07-04 00:16
ok i understand about the arcana spells being hard to add ill just turn the spells he wants into power myself. As for the erudite disciplines the erudite can learn discipline powers one level lower than the highest level power he can manifest, so for example he can learn a 7th level discipline power when he can manifest 8th level powers for reference it is on page 154 in complete psionics second column about 3 paragraphs down under learning discipline powers.

**Comment by BahamutDragon** [comment] 2015-07-04 00:36
I have all the PH spells up. Needs a good test. If you are on, then I will push the changes in and let you give it a spin.

**Comment by CyanideY** [comment] 2015-07-04 01:00
ya im around if you want to go ahead and push it ill give it a few test runs

**Comment by BahamutDragon** [comment] 2015-07-04 01:05
Spell display not working. SPELLLIST is Case Sensitive. Pushed in corrections. Gave it a quick test. Everything appears to be working. If you want to limit the spells allowed, or discipline powers that would be another request.

Grab the latest patch in branch 6.04.01

**Comment by CyanideY** [comment] 2015-07-04 01:36
i just grabbed the patch on branch 6.04.01 and did some testing. On my side there are no spells in the list with convert spell to power ACF on.

**Comment by BahamutDragon** [comment] 2015-07-04 01:42
Spell list will remain empty thankfully, since the purpose is to have the player actually select a spell or three. No need to overwhelm the player with additional choices.

When you added the Convert Spell to Power, did you notice the new category appear called "Erudite Arcane List"? Click on that, and you will notice your spells. Add the ones you want, they will automatically be granted to the character. I can force the 1 point to make it a bit more obvious in the future, forcing at least one selection if that would help.

**Comment by CyanideY** [comment] 2015-07-04 01:46
ok I see it now, I was not expecting it to be in the class features but from what I see everything is working as it should. Thanks for all the work you put into this it helps me out a lot.

**Comment by BahamutDragon** [comment] 2015-07-04 01:47
I'm working on setting up the Discipline Powers to be available to the Erudite next.

**Comment by BahamutDragon** [comment] 2015-07-07 06:53
Erudite already getting access to Discipline powers.

**Closed by BahamutDragon** 2015-07-07 06:53 UTC
Labels: enhancement, question, Request
