### ISSUE TITLE
[5e] Unable to choose a language

### ISSUE THREAD

**Issue by Proxxy0** [BahamutDragon/pcgen#724] opened 2017-07-10 00:29 UTC
I started to create a character, and everything seemed to work, except I was unable to pick a language, nor did I have any starting racial languages.

**Comment by BahamutDragon** [comment] 2017-07-10 04:35
Mate, can you please read what you wrote. Now, put yourself on my side of the screen and tell me if this report helps me figure out what the problem is? As it stands, I have a vague report about languages not working. If I open my version, make a default human and it works properly then where does that leave me? I end up closing this and stating that it works for me.  

What source books did you load? 
What race and selections did you make?

Anything else that can assist me?

Best,

**Comment by Proxxy0** [comment] 2017-07-10 13:07
Sorry, I was rushed, as I was about to play a campaign, and I wanted to get the issue in. I loaded the 5e player's handbook, monster manual, Volo's Guide, and all of the unearthed arcana sources. I made my character and went to look on the summary page. In the languages menu, it said I knew no languages (I was a tiefling fighter, and I did not even know common). I clicked the add a bonus language button, hoping that it would fix the issue, but when it opened, there were no languages in the menu. At this point, I figured that I might have bugged out the sources trying to make the character, so I reloaded them, and still, I knew no languages. I tried to make a new character to see if it was just something bugging for the tiefling, so I made a human fighter, but still, no languages were known.

**Comment by Proxxy0** [comment] 2017-07-16 04:39
Hey, I just loaded up That Old Black Magic, and updated my tiefling to abyssal, and it removed his both his infernal and common language and said that I had no languages, and I could not manually select common and abyssal through the bonus language menu.

**Comment by BahamutDragon** [comment] 2017-07-16 04:55
Mate, the subrace has the +1 to Con, grants Common and Abyssal as a language, and grants half the level in HP, min 1. 

Do you see Ability Score increase that states the Con score increases by 1, and the Language that says you can speak, read, and write abyssal?

I guess I should ask this, where exactly are you looking for these changes? If you review the character sheet, is your con score incorrect, and do you not have any languages displayed?

**Comment by Proxxy0** [comment] 2017-07-16 04:58
Yeah, first I looked at the summary page to see if everything updated correctly, and the modifier and languages were missing, so I then looked at the character sheet, and they were missing there too.

When I select the abyssal subrace all it says is:
All abyssal tieflings trace their bloodline to the demons of the Abyss. These tieflings have the following additional features.

**Comment by BahamutDragon** [comment] 2017-07-16 05:05
What version of pcgen are you using? 
Do you have any error messages in the log?

**Comment by BahamutDragon** [comment] 2017-07-16 05:10
Grab the updated set. The race traits will now show up.

**Comment by Proxxy0** [comment] 2017-07-16 05:15
Yep, that bit is fixed. Thanks!

**Comment by BahamutDragon** [comment] 2017-07-16 05:23
For the rest of the issues: Post a pdf export here of the character.

**Comment by BahamutDragon** [comment] 2017-07-16 05:23
along with the character pcg file.

**Comment by Proxxy0** [comment] 2017-07-16 05:28
Okay, so I re-opened the file that it was in, but now the languages are fixed. I think the update with the tiefling subraces fixed it as well, even though I am using the same sources as before. Again, thanks for the help!

**Comment by BahamutDragon** [comment] 2017-07-16 05:29
Resolved by minor edits.

**Closed by BahamutDragon** 2017-07-16 05:29 UTC
